torchrun --standalone --nnodes 1 --nproc-per-node 8 vla-scripts/train.py \
    --vla.type prism-qwen25-dinosiglip-224px+0_5b+mx-libero-90-aux \
    --vla.base_vlm /workspace/openvla-mini-aux/runs/prism-qwen25-extra-dinosiglip-224px+0_5b+stage-finetune+x7/ \
    --data_root_dir /datasets/libero/rlds/libero_aux_rlds \
    --vla.action_tokenizer libero_vq_extra_action_tokenizer \
    --vla.expected_world_size 8 \
    --vla.global_batch_size 256 \
    --vla.per_device_batch_size 32 \
    --run_id_note base \
    --run_id="libero_base" \
    --vla.transform_types="action" \
    --wandb_entity "jensen_team"