CUDA_VISIBLE_DEVICES=0 torchrun --standalone --nnodes 1 --nproc-per-node 1 vla-scripts/train.py \
    --vla.type prism-qwen25-dinosiglip-224px+0_5b+mx-xembod-robocasa-full \
    --vla.base_vlm /workspace/openvla-mini-aux/runs/prism-qwen25-extra-dinosiglip-224px+0_5b+stage-finetune+x7/ \
    --vla.data_mix panda+mg_lite \
    --data_root_dir /datasets/jensen/jensen_xembod_human_data \
    --vla.action_tokenizer mg_pnp_lite_vq_extra_action_tokenizer \
    --vla.expected_world_size 1 \
    --vla.global_batch_size 16 \
    --vla.per_device_batch_size 16 \
    --vla.lr_scheduler_type "constant" \
    --vla.max_steps 10000 \
    --vla.use_wrist_image False \
    --vla.image_sequence_len 1 \
    --wandb_entity="jensen_team" \
    --run_id_note "panda+mg_pnp_lite" \
    --run_id="debug" \
    --save_interval 1000 \
    --vla.transform_types="bbox->,low_level_motion->,ee_pose_2D->,action" \
    --dataset_statistics_map '{"panda_pnp": "mg_pnp_lite"}' \
    --pretrained_checkpoint "/workspace/openvla-mini-aux/runs/aux_only--mg_pnp_lite/checkpoints/step-050000-epoch-15-loss=0.0650.pt" \
    --is_resume False \
    --non_action_datasets '["mg_pnp_lite"]' \