torchrun --standalone --nnodes 1 --nproc-per-node 8 vla-scripts/train.py \
    --vla.type prism-qwen25-dinosiglip-224px+0_5b+mx-libero-90-aux \
    --vla.base_vlm /workspace/openvla-mini-aux/runs/prism-qwen25-extra-dinosiglip-224px+0_5b+stage-finetune+x7/ \
    --data_root_dir /datasets/libero/rlds/libero_aux_rlds \
    --vla.action_tokenizer libero_vq_extra_action_tokenizer \
    --vla.expected_world_size 8 \
    --vla.global_batch_size 128 \
    --vla.per_device_batch_size 16 \
    --run_id_note warmup+cosine_bs128 \
    --run_id="multitask" \
    --vla.transform_types="bbox,obj_pose,low_level_motion,ee_pose_2D,action" \
    --vla.transform_weights="0.1,0.1,0.1,0.1,0.6" \
    --vla.lr_scheduler_type="linear-warmup+cosine-decay" \
    --vla.warmup_ratio 0.02 \
    --vla.max_steps 400000 \
    --save_interval 100000 \
    --wandb_entity "jensen_team"