torchrun --standalone --nnodes 1 --nproc-per-node 8 vla-scripts/train.py \
    --vla.type prism-qwen25-dinosiglip-224px+0_5b+mx-xembod-robocasa-full \
    --vla.base_vlm /workspace/openvla-mini-aux/runs/prism-qwen25-extra-dinosiglip-224px+0_5b+stage-finetune+x7/ \
    --vla.data_mix mg_turn_on_sink_lite \
    --data_root_dir /datasets/jensen/jensen_xembod_human_data \
    --vla.action_tokenizer mg_turn_on_sink_lite_vq_extra_action_tokenizer \
    --vla.expected_world_size 8 \
    --vla.global_batch_size 256 \
    --vla.per_device_batch_size 32 \
    --vla.lr_scheduler_type "constant" \
    --vla.max_steps 15000 \
    --vla.use_wrist_image False \
    --vla.image_sequence_len 1 \
    --wandb_entity="jensen_team" \
    --run_id_note "mg_turn_on_sink_lite" \
    --run_id="ee" \
    --save_interval 5000 \
    --vla.transform_types="ee_pose_2D->,action" \
